[package]
name = "robe"
version = "0.1.0"
authors = ["Nicolas Sauzede <nsauzede@laposte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
